add laptop cfg

diff --git a/dotfiles/i3/scripts/openweather b/dotfiles/i3/scripts/openweather
--- a/dotfiles/i3/scripts/openweather
+++ b/dotfiles/i3/scripts/openweather
@@ -3,9 +3,9 @@
 
 temps=("#0600FF" "#0500FF" "#0400FF" "#0300FF" "#0200FF" "#0100FF" "#0000FF" "#0002FF" "#0012FF" "#0022FF" "#0032FF" "#0044FF" "#0054FF" "#0064FF" "#0074FF" "#0084FF" "#0094FF" "#00A4FF" "#00B4FF" "#00C4FF" "#00D4FF" "#00E4FF" "#00FFF4" "#00FFD0" "#00FFA8" "#00FF83" "#00FF5C" "#00FF36" "#00FF10" "#17FF00" "#3EFF00" "#65FF00" "#B0FF00" "#FDFF00" "#FFF000" "#FFDC00" "#FFC800" "#FFB400" "#FFA000" "#FF8C00" "#FF7800" "#FF6400" "#FF5000" "#FF3C00" "#FF2800" "#FF1400" "#FF0000")
 
-command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.
+command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.  
 Aborting."; exit 1; }
-command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.
+command -v wget >/dev/null 2>&1 || { echo >&2 "Program 'wget' required but is not installed.  
 Aborting."; exit 1; }
 
 # To use this script you need to create an API key here https://home.openweathermap.org
@@ -45,7 +45,7 @@ case $WEATHER_CONDITION in
     ;;
   'Drizzle')
     if [ "$DAYTIME" == "d" ]; then
-        WEATHER_ICON=""
+        WEATHER_ICON="" 
     else
         WEATHER_ICON=""
     fi
@@ -74,7 +74,7 @@ if [ "$WEATHER_INT" -lt "-11" ]; then
 elif [ "$WEATHER_INT" -gt 35 ]; then
     WEATHER_COLOR="#FF0000"
 else
-    WEATHER_INT=$(( WEATHER_INT + 11 ))
+    WEATHER_INT=$(( WEATHER_INT + 11 )) 
     WEATHER_COLOR="${temps[$WEATHER_INT]}"
 fi
 
